config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  match '/auth/twitter/callback', to: 'sessions#create', via: 'get'
  match '/auth/failure', to: redirect('/'), via: 'get'
  namespace :admin do
   mount Sidekiq::Web => '/sidekiq'
   get '', to: 'dashboard#index', as: '/'
   get 'all_user', to: 'dashboard#all_user'
   get 'create_content_for_user/:id', to: 'dashboard#create_content_for_user', as: 'create_content_for_user'
   resources :categories
   resources :sources
   resources :feeds, except: [:show, :index]
  end

  namespace 'api' do
    namespace 'v1' do
      resources :events
      resources :feeds
      get 'search', to: 'feeds#search'
      resources :categories
    end
  end

  devise_for :users
  root 'feeds#index'
  resources :users,  only: [:update] do
    member do
      get 'profile'
      get 'profile_setup'
      #get '/auth/twitter/callback', to: 'users#callback'
    end
  end
  get 'search', to: 'feeds#search', as: 'search'
  resources :feeds  do
      resources :comments
      collection do
        get 'my_feeds'
      end
      member do
        get 'favorite'
      end
  end
  resources :events
  resources :categories, only: [:show]
end

app/models/feed.rb
class Feed < ApplicationRecord

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to              :source
  has_and_belongs_to_many :users
  has_many                :comments, dependent: :destroy

  scope :default, -> { order("created_at DESC") }
  scope :current_page, -> (page) do
    paginate(:page => page, :per_page => per_page)
  end

  def self.per_page
    20
  end
end

app/controllers/admin/feeds_controller.rb
class Admin::FeedsController < Admin::AdminController
   before_action :set_feed, only: [:destroy]
    def update_news
       get_rss
       respond_to do |format|
         format.html { redirect_to feeds_url, success: 'Новости успешно добавлены.' }
         format.json { head :no_content }
       end
    end

    def edit

    end
    def destroy
      @feed.destroy
      respond_to do |format|
        format.html { redirect_to feeds_url, success: 'Новость успешно удалена' }
        format.json { head :no_content }
      end
    end
    private

    def set_feed
        @feed = Feed.find(params[:id])
    end

end

app/controllers/api/v1/feeds_controller.rb
module Api
  module V1
    class FeedsController < ApplicationController

      def index
         @feeds = Feed.order('created_at DESC').first(5)
      end

      def search
         @feeds = SearchFilter.new(params[:title_search]).scope if params[:title_search]
         #@feeds = Feed.all.first(5)
      end

    end
  end
end

app/controllers/feeds_controller.rb
require 'twitter'
class FeedsController < ApplicationController
 before_action :authenticate_user!, except: [:index, :show, :search]
 before_action :set_feed, only: [:destroy, :show, :edit, :favorite, :update]
 before_action :top_feeds, only: [:index, :my_feeds]

  def index
    @sourse = Source.all
    @feeds = SearchFilter.new(params[:filter]).scope.current_page(params[:page]) if params[:filter]
    @feeds = SearchFilter.new(params[:title_search]).scope.current_page(params[:page]) if params[:title_search]
    @feeds  = Feed.current_page(params[:page]).order("created_at DESC") unless params[:filter] || params[:title_search]
    @caterories = Category.all
  end
  def search 
    @feeds = SearchFilter.new(params[:title_search]).scope.current_page(params[:page]) if params[:title_search]
    render json: @feeds
  end 
  def show
    @categories = Category.all.order("view_count DESC")
    add_view_to_feed(@feed)
    unless @feed
      render text: "PAge not found", status: 404
    end
  end

  def new
    @feed = Feed.new
    authorize! :new, Feed
  end

  def my_feeds
      @feeds = Feed.where(source_id: current_user.sourse_mass_id ).order("created_at DESC")
        .paginate(:page => params[:page], :per_page => 20)
      last_seen
  end

  def favorite
     add_or_destroy_favorite(@feed)
  end

  def update_news
     get_rss
     respond_to do |format|
       format.html { redirect_to feeds_url, notice: 'Новости успешно добавлены.' }
       format.json { head :no_content }
     end
  end

  def edit
    authorize! :edit, @feed
  end

  def create
    #add_params_to_create_hash
    @feed = Feed.new(feed_params)
    respond_to do |format|
      if @feed.save
        format.html { redirect_to feed_path(@feed), success: 'Новость успешно создона.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new, danger: 'Новость не создона '  }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
    authorize! :create, Feed
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to feed_path(@feed), success: 'Новость успешно обновлена.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit, danger: 'Новость не добавлена.' }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
    authorize! :update, @feed
  end
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, success: 'Новость успешно удалена' }
      format.json { head :no_content }
    end
    authorize! :destroy, @feed
  end
  private



  def add_params_to_create_hash(create_params)
    fix_params = {source_id: 3}
    create_params.marge(fix_params)
  end

  def set_feed
      @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:title, :link, :data_time, :description, :full_description, :source_id, :image)
  end

  def add_or_destroy_favorite (feed)
    if current_user.feeds.ids.include?(feed.id)
      current_user.feeds.delete(feed)
      redirect_to feed_url(feed), success: "Новость удалина из избранных"
    else
      current_user.feeds.push feed
      redirect_to feed_url(feed), success: "Новость добавлена в избраное"
    end
  end

  def add_view_to_feed (feed)
    feed = feed.increment(:view_count)
    feed.save
    feed.source.categories.each do |category|
      category.increment(:view_count)
      category.save
    end
  end

  def last_seen
    @user = current_user
    @user.last_visit = Time.now
    @user.save
  end

end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_feed.html.erb
<div class="item">
  <div class="feed-date">
    <%= feed.data_time.strftime("%I:%M %d-%m-%Y") %>
    <a href="<%= feed.link %>" class="feed-link">Оригинал</a>
    <span class="pull-right"><%= social_share_button_tag( feed.title ) %> </span>
  </div>
  <div class="feed-title">
    <%= link_to feed.title, feed, class: "feed-link"%>
  </div>
  <div style="clear:both;"></div>

  <div class="feed-mini-description">
    <p ><%= strip_tags(feed.description).slice(0..100)  %>...</p>
  </div>
  <div class="feed-img">
     <img src="<%= feed.image %>">
  </div>
  <div class="feed-footer">
    <i class="fa fa-commenting" aria-hidden="true"> <%= feed.comments.size %></i>
    <i class="fa fa-eye" aria-hidden="true"> <%= feed.view_count%></i>
    <% if can? :edit, feed %>
      <%= link_to "Редактировать", edit_feed_path(feed), class: "feed-link"%>
    <% end %>
    <%if can? :destroy, feed %>

        <%= link_to 'Удалить', feed_path(feed), method: :delete, data: { confirm: 'Are you sure?' }, class: "feed-link" %>
    <% end %>
  </div>
</div>

app/views/feeds/_form.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <%= form_with(model: feed, local: true) do |f| %>
      <% if feed.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>
          <ul>
          <% feed.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label 'Название новости' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label 'Ссылка на картинку' %>
        <%= f.text_field :image, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label 'Краткое содержание' %>
        <%= f.text_area :body, class: " text-area-comment " %>
      </div>
      <div class="textarea-form">
        <%= f.label 'Содержание новости ' %>
        <%= f.trix_editor :full_description, class: 'editor' %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/feeds/edit.html.erb
<h1>Редактор новости</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<div class="row">
  <div class="col-md-8 feeds-wrapper">
    <section id='feeds'>
      <%= render partial: 'feed', collection: @feeds%>
    </section>
  </div>
  <div class="col-md-4 top-feed-wrap">
    <%= render 'shared/top_feeds'%>
  </div>
</div>
<%= will_paginate @feeds %>

app/views/feeds/my_feeds.html.erb
<div class="row">
  <div class="col-md-8 feeds-wrapper">
    <section id='feeds'>
      <%= render partial: 'feed', collection: @feeds%>
    </section>
  </div>
  <div class="col-md-4 top-feed-wrap">
    <%= render 'shared/top_feeds'%>
  </div>
</div>
 <!-- </div> -->


<%= will_paginate @feeds %>

app/views/feeds/my_feeds.js.erb
$('#feeds').append("<%=j render(@feeds) %>");
<% if @feeds.next_page %>
    $('.pagination').replaceWith("<%= j will_paginate @feeds %>");
<% else%>
    $('.pagination')remove();
<% end %>

app/views/feeds/search.html.erb
<section id='feeds'>
  <div class="masonry container-fluid">
    <%= render partial: 'feed', collection: @feeds%>
  </div>
</section>

app/views/feeds/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="show-news-img-wrap">
      <img src="<%= @feed.image %>" alt="" class="show-news-img">
    </div>
    <h4><%= @feed.title %></h4>
    <p class="view_and_comment">
    <span><i class="fa fa-calendar" aria-hidden="true"></i> <%= @feed.data_time.to_date.strftime("%d-%m-%Y") %></span>
    <span><i class="fa fa-eye" aria-hidden="true"> </i> <%= @feed.view_count %></span>
    <span><i class="fa fa-commenting" aria-hidden="true"></i> <%= @feed.comments.size %></span>
    <span class="favorite">
      <% if user_signed_in? %>
        <%@user = User.find(current_user.id)%>
          <%if @user.feeds.ids.include?(@feed.id) %>
            <a class="favorite" href="<%= favorite_feed_path(@feed.id) %>" title="Удалить из избранного">
              <i class="fa fa-star" aria-hidden="true"></i> Удалить из избранного</a>
          <% else %>
            <a class="favorite" href="<%= favorite_feed_path(@feed.id) %>" title="Добавить в избранное">
              <i class="fa fa-star-o" aria-hidden="true"></i> Добавить в избранное</a>
          <% end %>
        <% end %>
    </span>
    </p>
    <div class="content-feed">
    <% if @feed.full_description.blank? %>
      <%= @feed.description.html_safe%>
    <%else%>
      <%= @feed.full_description.html_safe%>
    <%end%>
      
    </div>
    <%= render 'shared/comment'%>
  </div>
  <div class="col-md-4">
    <h5 style="text-align:center;">Вам может понравится</h5>
    <%= render 'shared/might_like'%>
  </div>
</div>
<% if can? :update, current_user %>
<%= link_to 'Edit', edit_admin_feed_path(@feed) %> 
<% end %>