config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  match '/auth/twitter/callback', to: 'sessions#create', via: 'get'
  match '/auth/failure', to: redirect('/'), via: 'get'
  namespace :admin do
   mount Sidekiq::Web => '/sidekiq'
   get '', to: 'dashboard#index', as: '/'
   get 'all_user', to: 'dashboard#all_user'
   get 'create_content_for_user/:id', to: 'dashboard#create_content_for_user', as: 'create_content_for_user'
   resources :categories
   resources :sources
   resources :feeds, except: [:show, :index]
  end

  namespace 'api' do
    namespace 'v1' do
      resources :events
      resources :feeds
      get 'search', to: 'feeds#search'
      resources :categories
    end
  end

  devise_for :users
  root 'feeds#index'
  resources :users,  only: [:update] do
    member do
      get 'profile'
      get 'profile_setup'
      #get '/auth/twitter/callback', to: 'users#callback'
    end
  end
  get 'search', to: 'feeds#search', as: 'search'
  resources :feeds  do
      resources :comments
      collection do
        get 'my_feeds'
      end
      member do
        get 'favorite'
      end
  end
  resources :events
  resources :categories, only: [:show]
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :sources
  validates :name, presence:  true
end

app/views/shared/_admin_index.html.erb
<div class="row dashboard-content shadow">
  <div class="col-md-6">
    <% @categories.each do |category|%>
    <span style="font-size: 16px; font-weight:600;"><%= category.name%>:</span> <span><%= category.view_count %> просмотров</span>
      <div class="progress progress-line" style="width:100%;">
        <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"
        style="width: <%=(category.view_count * 100)/ @all_category_count %>%;">
        <%=(category.view_count * 100)/ @all_category_count %>%
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-6 dashboard-content-stats">
    <div class="user-online shadow" style="background-color: #3495d6;">
      <p><%= User.online.size %></p>
      <span>  Пользователей онлайн</span>
      <i class="fa fa-users" aria-hidden="true"></i>
    </div>
    <div class="user-online shadow" style="background-color: #28b779;">
      <% a = Feed.where('created_at >= ? AND created_at < ?', Time.current.beginning_of_day, Time.current.beginning_of_day + 1.day)%>
      <p><%= a.size %></p>
      <span>Новостей за 24 часа</span>
      <i class="fa fa-newspaper-o" aria-hidden="true"></i>
    </div>
    <div class="user-online shadow" style="background-color: #9a59b5;">
      <% a = Feed.where('created_at >= ? AND created_at < ?', Time.current.beginning_of_day, Time.current.beginning_of_day + 1.day)%>
      <p><%= Feed.all.size %></p>
      <span>Всего новостей в базе</span>
      <i class="fa fa-newspaper-o" aria-hidden="true"></i>
    </div>
  </div>
</div>

app/views/shared/_categories.html.erb
<ul class="top-bar-items" style="padding: 0 ;">
  <% @caterories = Category.all%>
  <% @caterories.each do |category|%>
     <li><%= link_to category.name, category_path(category)%></li>
  <%end%>
</ul>

app/views/shared/_comment.html.erb
<div class="container comment-wrapper">
<% if user_signed_in? %>
  <h2>Добавить комментарий:</h2>
  <%= form_with(model: [ @feed, @feed.comments.build ], local: true) do |f| %>
    <%= image_tag current_user.avatar.url(:thumb), class: "user_icon"  if current_user.avatar? %>
    <br>
    <p>
      <%= f.text_area :body, class: "text-area-comment", placeholder: "Текст комментария" %>
    </p>
    <p style="float:right;"><%= f.submit 'Добавть комментарий', class: 'btn btn-success' %></p>
    <div style="clear: right;"></div>
  <% end %>
<% end %>
<h3>Коментарии:</h3>
<% @feed.comments.reject{|e| e.new_record? }.each do |comment| %>
   <div class="comment">
     <div class="comment-author">
       <span style="font-weight:600; font-size:16px;">Автор: <%= comment.author %></span>
       <span style="float:right;">
           <% if can? :delete, comment %>
             <%= link_to '', [comment.feed, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "delate_comment fa fa-times" %>
           <% end %>
       </span>
     </div>
     <div class="comment-body">
       <p>
         <%= comment.body %>
       </p>
         <span style="float:right;"><%= comment.created_at.strftime("%I:%M %d-%m-%Y") %></span>
     </div>
   </div>
<% end %>
</div>

app/views/shared/_dashboard_nav_bar.html.erb
<div class="dashboard-bar shadow">
  <img src="http://www.thepixelfarm.co.uk/wp-content/uploads/2016/05/admin_v01D_support.png" alt="">
  <ul class="dashboard-bar-list ">
    <li><a href="<%= admin_path %>"><i class="fa fa-tachometer" aria-hidden="true"></i> Панель</a></li>
    <li><a href="<%= admin_categories_path %>"><i class="fa fa-list" aria-hidden="true"></i>  Категории</a></li>
    <li><a href="<%= admin_sources_path %>"><i class="fa fa-cloud" aria-hidden="true"></i>  Источники</a></li>
    <li><a href="<%= admin_all_user_path%>"><i class="fa fa-users" aria-hidden="true"></i>  Пользователи</a></li>
    <li><a href=""><i class="fa fa-newspaper-o" aria-hidden="true"></i>  Загрузить новости</a></li>
    <li><a href=""><i class="fa fa-money" aria-hidden="true"></i>  Обновить курс валют</a></li>
  </ul>
</div>

app/views/shared/_filter_window.html.erb
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close " data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <%= render 'shared/search'%>
    </div>
  </div>
</div>

app/views/shared/_header_other.html.erb
<div class="container-fluid header3">
  <div class="row">
    <div class="col-md-6">
        <div class="filter-and-search">
          <%= form_with  url: feeds_path, method: "Get",html: { id: 'form-search' } , local: true  do |f| %>
              <input id="who" type="text" class="search-input" name="title_search" placeholder="Поиск" required>
              <input type="submit"   class="search-btn" value="">
          <% end %>
          <% if(current_user) %>
            <div class="filter-btn">
              <a href="javascript:void(0);" id="filter" data-toggle="modal" data-target=".bs-example-modal-lg"><i class="fa fa-filter" aria-hidden="true"></i> Фильтр</a>
            </div>
            <%= render 'shared/filter_window'%>
          <% end %>
        </div>
        <div class="fast-search">
           <div id="search_advice_wrapper"></div>
        </div>
    </div>
    <div class="col-md-3">
      <div class="filter-and-search">

      </div>
    </div>
    <div class="col-md-3">
      <div class="filter-and-search">
        <div class="row">
           <div class="col-md-8 user_menu">
             <ul>
               <%if user_signed_in? %>
               <li><%=link_to '<i class="fa fa-sign-out" aria-hidden="true"></i> Выйти'.html_safe, destroy_user_session_path , method: :delete%></li>
               <li><%=link_to '<i class="fa fa-user" aria-hidden="true"></i> Профайл'.html_safe, profile_user_path(current_user.id) %></li>
               <li><%=link_to "<i class='fa fa-cog' aria-hidden='true'></i> Настройки".html_safe, profile_setup_user_path(current_user.id)%></li>
               <% else %>
                <li><%=link_to '<i class="fa fa-sign-in" aria-hidden="true"></i> Войти'.html_safe, new_user_session_path%></li>
                <li><%=link_to '<i class="fa fa-user-plus" aria-hidden="true"></i> Регистрация'.html_safe, new_user_registration_path%></li>
               <% end %>
             </ul>
           </div>
           <div class="col-md-4 user_logo_wrap">
             <%if user_signed_in? %>
               <div class=" user_logo ">
                 <a href="<%= profile_user_path(current_user.id)%>">
                 <%= image_tag current_user.avatar.url(:thumb),:style => "" if current_user.avatar?%>
                 </a>
               </div>
            <% end %>
           </div>

        </div>
      </div>
    </div>
    <div class="col-md-12 categories-list">
      <%= render 'shared/categories'%>
    </div>
  </div>
</div>
<script type="text/javascript">
  $("#who").bind("input ", function() {
    if(this.value.length >= 2){
        $.ajax({
            type: 'GET',
            url: "/search", 
            data: {'title_search':this.value},
            success: function(data){
              $("#search_advice_wrapper").html('');
              for(i in data){
                $("#search_advice_wrapper").append('<a class="feed-link" href=/feeds/'+data[i]["id"]+'><div class="advice_variant"><img src='+data[i]["image"]+'><span>'+data[i]["title"].substring(0, 50)+'...</span></div></a>').show(600);
              }
             console.log( data ); 
           }
       });
    }
  });

  $( "#who" ).focusout(function() {
     $(".advice_variant").hide(500);
  });
  $( "#who" ).focus(function() {
     $(".advice_variant").show(500);
  });
</script>

app/views/shared/_might_like.html.erb
<% @categories.each do |category| %>
  <h3><%= category.name  %></h3>
  <%  @might_like = Feed.where("source_id IN (?)", category.source_ids).order("view_count DESC").first(4)%>
  <div class="row">
    <% @might_like.each do |feed| %>
        <div class="col-md-6">
          <a href="<%= feed_path(feed) %>" class="mini-link">
            <div class="mini-item">
              <div class="mini-item-img">
                 <img src="<%= feed.image %>">
              </div>
              <div>
                <span><i class="fa fa-commenting" aria-hidden="true"></i> <%= feed.comments.size %></span>
                <span><i class="fa fa-eye" aria-hidden="true"></i> <%= feed.view_count %> </span>
                <p class="mini-item-title" ><%= link_to feed.title, feed %></p>
              </div>
            </div>
          </a>
        </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_my_comments.html.erb
<div class="profile_comment">
    <h4>Ваши комментарии:</h4>
     <% @user.comments.each do |user_comment| %>
        <%= link_to 'Show', feed_url(user_comment.feed_id) %>
        <span>имя:</span><%=user_comment.author%><br>
        <span>комментарий:</span>  <%=user_comment.body%>   <br> <br>
     <%end%>
</div>

app/views/shared/_my_favorite.html.erb
<div class="">
    <div class="favorite_feed">
      <h4>Избранное:</h4>
      <div class="row">
         <% @user.feeds.each do |favorite| %>
               <div class="col-md-3 favorite_feed_item">
                  <img src="<%= favorite.image%>" alt="" >
               </div>
               <div class="col-md-9 favorite_feed_title favorite_feed_item">
                 <p><%= link_to favorite.title, feed_path(favorite.id) if favorite.image?%></p>
                 <%= favorite.description.slice(0..150)%>
               </div>
         <%end%>
       </div>
    </div>
</div>

app/views/shared/_my_profile.html.erb
<div class="profile_icon">
  <%= image_tag @user.avatar.url(:thumb), :style => "width: 100px;height: 100px; border-radius:55px;"  if @user.avatar? %><br>
  <h3><%= @user.first_name %> <%= @user.last_name %></h3>
  <%= @user.email %><br>
  <div class="user_profile_btn">
    <a href="<%= profile_setup_user_path(current_user.id) %>" class="user_settings"><i class="fa fa-cog" aria-hidden="true"></i> Настройки</a>
    <a href="<%= %>" class="user_sign_out"><i class="fa fa-sign-out" aria-hidden="true"></i></a>
    <% if @user.admin%>
    <div class="">
      <a href="<%= admin_path%>" class="admin-link">Панель администратора</a>
    </div>
    <% end %>
  </div>
</div>


<div class="user_source">
  <h3>Ваши источники:</h3>
  <% @source = Source.where(" id IN (?)", @user.sourse_mass_id) %>
    <ul>
      <% @source.each do |source| %>
        <li><i class="fa fa-angle-right" aria-hidden="true"></i> <%= source.name%></li>
      <% end %>
    </ul>
</div>

app/views/shared/_nav_header.html.erb
<div class="container-fluid header">
 <div class="row">
     <div class="col-md-12 nav-nemu">
          <div class="logo pull-left">
             <img src="https://dec-edu.com/uploads/images/news-logo.png">
          </div>
          <div class="top-bar ">
           <ul class=" top-bar-items">
             <li><%= link_to 'Все новости', feeds_path %></li>
             <li><%= link_to 'События', events_path%></li>
             <li><a href="<%=my_feeds_feeds_path %>">Моя лента</a></li>
             <% if user_signed_in? %>
             <li>
               <p class="badge-top">
                <%= new_feed_count(current_user) %>
               </p>
             </li>
             <% end %>
             <ul class="social-link-top">
             <li><a href=""><i class="fa fa-paper-plane" aria-hidden="true"></i></a></li>
             <li><a href=""><i class="fa fa-facebook-square" aria-hidden="true"></i></a></li>
             <li><a href=""><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
             <li><a href=""><i class="fa fa-google-plus-official" aria-hidden="true"></i></a></li>
             </ul>

           </ul>
           <div class="rates pull-right">
             <ul class="top-bar-items">
               <% rates = Rate.last(3)
                  rates.each do |rate|  %>
                     <li><span><%= rate.title %>  <%= eval(sprintf("%8.3f",rate.rate))  %></span></li>
               <% end %>
              </ul>
           </div>
          </div>
     </div>
   </div>
 </div>

app/views/shared/_search.html.erb
<div class="search_form">
  <% @categories = Category.all %>
    <%=form_for :filter, url: url_for( :controller => :feeds, :action => :index ), method: "Get", local: true do |f| %>
        <%= f.text_field :title_search, class: 'search-input', placeholder: "Поиск" %>
        <div class=" row filter-checkbox">
          <% @categories.each do |category| %>
            <div class="category-search">
              <div class=" checkbox">
                <label><%= f.check_box(  :category, {:multiple => true}, category.id , nil)%> <%=  category.name %></label>
              </div>
            </div>
          <% end %>
        </div>
        <div class="row">
          <div class="col-md-6 filter-calendar-wrap">
            <p>От:</p>
            <%= f.text_field :start_date, id: "datepicker", class: "filter-calendar", placeholder: "Начальная дата"  %>
            <i class="fa fa-calendar" aria-hidden="true"></i>
          </div>
          <div class="col-md-6 filter-calendar-wrap">
            <p>До:</p>
            <%= f.text_field :end_date, id: "datepicker1", class: "filter-calendar", placeholder: "Конечная дата" %>
            <i class="fa fa-calendar" aria-hidden="true"></i>
          </div>
        </div>
        <div class="filter-submit">
            <%= f.submit 'Поиск', class: 'btn'%>
        </div>
    <% end %>
</div>

<script type="text/javascript">
  $(function() {
    $("#datepicker").datepicker();
    $("#datepicker1").datepicker();
  });
</script>

<!-- f.date_field -->

app/views/shared/_top_feeds.html.erb
<h5 style="text-align: center;">Популярное сейчас</h5>
<% @top_feeds.each do |feed| %>
  <a href="<%= feed_path(feed) %>" class="mini-link">
    <div class="mini-item">
      <div class="mini-item-img">
         <img src="<%= feed.image %>">
      </div>
      <div>
        <span><i class="fa fa-commenting" aria-hidden="true"></i> <%= feed.comments.size %></span>
        <span><i class="fa fa-eye" aria-hidden="true"></i> <%= feed.view_count %> </span>
        <p class="mini-item-title" ><%= link_to feed.title, feed %></p>
      </div>
    </div>
  </a>
<% end %>

app/views/shared/_twitter_list.html.erb
<% if user_signed_in?%>
  <div class="col-md-2 twitter_list" style="padding: 0;">
      <div class="twitter-content shadow">
        <% current_user.tweets.order(created_at: :desc).each do |tweet|%>
          <div class="twitter-item">
            <img src="<%= tweet.profile_image_url %>" style="border-radius: 40px" alt="">
            <a href="<%= tweet.user_url %>" class="feed-link" style="padding-left: 10px;">@<%= tweet.user_screen_name %></a>
            <a href="<%= tweet.url %>" class="feed-link" >
              <p style="padding-top: 10px;"><%= tweet.full_text %></p>
            </a>
          </div>
        <%end %>
      </div>
  </div>
<% end %>