config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  match '/auth/twitter/callback', to: 'sessions#create', via: 'get'
  match '/auth/failure', to: redirect('/'), via: 'get'
  namespace :admin do
   mount Sidekiq::Web => '/sidekiq'
   get '', to: 'dashboard#index', as: '/'
   get 'all_user', to: 'dashboard#all_user'
   get 'create_content_for_user/:id', to: 'dashboard#create_content_for_user', as: 'create_content_for_user'
   resources :categories
   resources :sources
   resources :feeds, except: [:show, :index]
  end

  namespace 'api' do
    namespace 'v1' do
      resources :events
      resources :feeds
      get 'search', to: 'feeds#search'
      resources :categories
    end
  end

  devise_for :users
  root 'feeds#index'
  resources :users,  only: [:update] do
    member do
      get 'profile'
      get 'profile_setup'
      #get '/auth/twitter/callback', to: 'users#callback'
    end
  end
  get 'search', to: 'feeds#search', as: 'search'
  resources :feeds  do
      resources :comments
      collection do
        get 'my_feeds'
      end
      member do
        get 'favorite'
      end
  end
  resources :events
  resources :categories, only: [:show]
end

app/models/event.rb
class Event < ApplicationRecord
  serialize :city, Hash
end

app/controllers/api/v1/events_controller.rb
module Api
  module V1
    class EventsController < ApplicationController
      def index
        @events = Event.order('created_at DESC')
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_event, only: [:destroy, :show, :edit]

  def index
     @events = Event.all

  end

  def show

  end

  def edit

  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, success: 'Событие успешно удалено' }
      format.json { head :no_content }
    end
  end

  private

    def set_event
      @event = Event.find(params[:id])
    end

end

app/views/events/index.html.erb
<div class="masonry container-fluid">
    <% @events.each do |event| %>
       <div class="item">
           <div class="img-hover">
           <span class="desc"><p style="padding:5px;"><%= strip_tags(event.description).slice(0..100) %>...</p></span>
           <img src="https://d.wildapricot.net/images/newsblog/bigstock-events-7444309.jpg">
            </div>
            <div class="read">
              <%= link_to "<i class='fa fa-angle-right' aria-hidden='true'></i>".html_safe, event %>
            </div>
            <%= link_to event.title, event, class: "item-link" %>
            <div class="item-info events-info">
              <p><i class="fa fa-calendar" aria-hidden="true"></i> Время начала: <%= event.start_time.to_date.strftime("%d-%m-%Y %I:%M") %></p>
              <p><i class="fa fa-calendar" aria-hidden="true"></i> Время окончания: <%= event.end_time.to_date.strftime("%d-%m-%Y %I:%M")%></p>
              <p>Город: <%= event.city["city"]%></p>
              <p>Страна: <%= event.city["country"]%></p>
              <p>Улица: <%= event.city["street"]%></p>
            </div>
            <%= link_to 'Удалить', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %>
            <br><%= social_share_button_tag( event.title ) %>
        </div>
    <% end %>
 </div>

app/views/events/show.html.erb
<div class="row">
  <div class="col-md-8">
    <h4><%= @event.title %></h4>
    <p>Город: <%= @event.city["city"]%></p>
    <p>Страна: <%= @event.city["country"]%></p>
    <p>Улица: <%= @event.city["street"]%></p>
    <p>Время начала: <%= @event.start_time.to_date.strftime("%I:%M %d-%m-%Y") %></p>
    <p>Время окончания: <%= @event.end_time.to_date.strftime("%I:%M %d-%m-%Y")%></p>
    <p><a href="<%= @event.link%>">оригинал</a></p>
    <%= @event.description%>
  </div>
</div>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>